// <auto-generated />
using Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Database.Migrations
{
    [DbContext(typeof(LocalContext))]
    partial class LocalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Business.Models.Log", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Event")
                        .HasColumnType("INT(3)");

                    b.Property<int>("Level")
                        .HasColumnType("INT(1)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("UserHash")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Hash");

                    b.HasIndex("UserHash");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Business.Models.User", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Hash");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Business.Models.Log", b =>
                {
                    b.HasOne("Business.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserHash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
